### ISSUE TITLE
NestJS Passport JWT: Error - Unknown authentication strategy 'jwt'

### ISSUE THREAD

**Issue by JDCodeWork** [JDCodeWork/afp#1]
I'm working on a NestJS application that uses Passport and JWT for authentication. The implementation was working perfectly until recently, when I started getting the following error when trying to authenticate requests with a JWT token:

```less
ERROR [ExceptionsHandler] Unknown authentication strategy "jwt"
Error: Unknown authentication strategy "jwt"
    at attempt (/path/to/node_modules/passport/lib/middleware/authenticate.js:193:39)
    at authenticate (/path/to/node_modules/passport/lib/middleware/authenticate.js:379:7)
    at /path/to/node_modules/@nestjs/passport/dist/auth.guard.js:88:3
    at new Promise (<anonymous>)
    at /path/to/node_modules/@nestjs/passport/dist/auth.guard.js:80:83
    at MixinAuthGuard.canActivate (/path/to/node_modules/@nestjs/passport/dist/auth.guard.js:44:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
```
The error occurs whenever I try to access a route that requires JWT authentication.

What I’ve Tried
I attempted the following steps to resolve the issue:

Ensured that the JwtStrategy is registered in the AuthModule.

Verified that the SECRET_KEY is properly set in the environment variables.

Reinstalled dependencies to ensure compatibility
Logged the initialization of the JwtStrategy to confirm that it is being registered, but it seems like it is not loading correctly.
Checked the imports and exports in the AuthModule.

I expect the authentication to work, allowing protected routes to verify and decode JWT tokens successfully.

**Comment by JDCodeWork** [comment]
The error was solved by removing the dependencies of jwt.strategy to commonService and usersService using directly the repository and using the static method of commonService to get the error message, I still don't know why this error happens but the JWT reading is working again.
